### ISSUE TITLE
Is there a way to for leader-line to know when the element it is pointing to is hidden by overflow?

### ISSUE THREAD

**Issue by frumbert** [anseki/leader-line#104]
I modified your position example in the documentation so the overflowing scroll element is wider such that the scrolling causes the end node to be hidden by object overflow.

![scroll-this-overflow](https://user-images.githubusercontent.com/592257/74601917-5582c880-50f7-11ea-817e-7c891669e9f3.gif)

Would it be possible to continue to have the leader line point to the nearest position in the overflowing object? (e.g. have the arrow point to the left edge after the end node becomes hidden) ? What approach would I start with?

The behaviour is also apparent in your startsocket drag example, where the leader-line begins from a point you can't temporarily see:

![drag-example](https://user-images.githubusercontent.com/592257/74601971-fec9be80-50f7-11ea-99db-a05e4dcbe9c2.gif)

**Comment by anseki** [comment]
Hi @frumbert, thank you for the comment.
Could you show me that code in https://jsfiddle.net/ ?

**Comment by frumbert** [comment]
Uh, the first example is your code at https://anseki.github.io/leader-line/#position, where I merely changed the element style to be wider
```css
#ex-140-frame > div {
    width: 700px;
    height: 100%;
    background-color: #f0f0f0;
}
```
changed to
```css
#ex-140-frame > div {
    width: 1700px;
    height: 100%;
    background-color: #f0f0f0;
}
```
